spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/fake?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
fake:
  mapper:
    mapper-packages: org.throwable.fake.configuration.mapper
    mapper-locations: mappings/*.xml
    enable-pagination-plugin: false
    enable-sql-statistics-plugin: false
    check-configuration-location: true
    configuration-location: classpath:configuration/mybatis-configuration.xml
  druid:
    configuration:
        primary-doge:
            primary: true
            url: jdbc:mysql://localhost:3306/fake?useSSL=false
            driverClassName: com.mysql.jdbc.Driver
            password: root
            username: root
            properties:
                filters: stat
    enable-stat-filter: false
    enable-stat-view: false

